version: 2.2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/ProjectManagement

    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install dependencies
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      
      - run:
        name: test
        command: npm test
      
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
        path: coverage
        prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
        path: test-results.xml