# Python CircleCI 2.0 configuration file
version: 2.2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/ProjectManagement

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'