version: 2.1
jobs:
  build:
    working_directory: ~/ProjectManagement
    docker:
        - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install npm
          command: sudo npm install 
      
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths: 
            - ./node_modules 
      
      - run:
          name: test
          command: npm test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml
      - run:
            name: run ESLint
            command: npm run lint   
